import pytest

# V52.9.201 — Ces contrôles validaient explicitement des écrans/versions désormais retirés.
# Ils restent dans le dépôt comme historique, mais ne font plus partie du contrat V1 Virage Serré.
LEGACY_V201_RETIRED = {
    'api/tests/test_e7_ghost_cleanup.py::test_launcher_forces_fresh_test_navigation',
    'api/tests/test_e7_prepare_back_cleanup.py::test_prepare_return_has_explicit_cleanup_authority',
    'api/tests/test_e7_prepare_decap.py::test_prepare_uses_fresh_css_token_and_historical_open_order',
    'api/tests/test_e7_prepare_surface_scope.py::test_vehicle_continue_calls_mobile_navigation',
    'api/tests/test_e7_prepare_surface_scope.py::test_mobile_navigation_open_reaches_prepare',
    'api/tests/test_e7_state_controller_clean.py::test_open_restores_historical_prepare_order_then_refreshes_visible_map',
    'api/tests/test_e7_vehicle_chain_regression.py::test_vehicle_to_prepare_chain_has_no_intermediate_prepare_overlay',
    'api/tests/test_launcher_fresh_build.py::test_launcher_uses_fresh_geocoding_build_token',
    'api/tests/test_restrictions_ui_block.py::test_restrictions_alertes_et_themes_local',
    'api/tests/test_restrictions_ui_block.py::test_v52_vehicle_garage_is_between_home_and_map',
    'api/tests/test_restrictions_ui_block.py::test_v52_supports_five_saved_vehicles_default_and_temporary',
    'api/tests/test_v529102_overlay_siblings.py::test_floating_trip_overlay_is_sibling_of_mobile_nav_and_selector_targets_sibling',
    'api/tests/test_v529102_overlay_siblings.py::test_floating_bus_stop_is_sibling_and_selector_targets_sibling',
    'api/tests/test_v529124_dynamic_driving_horizon.py::test_dynamic_horizon_is_speed_based_and_bounded',
    'api/tests/test_v529176_selection_tournee_ready.py::test_v176_vehicle_selection_is_reinforced',
    'api/tests/test_v529176_selection_tournee_ready.py::test_v176_ready_landscape_single_compact_bar',
    'api/tests/test_v529199_virage_deux_vues.py::test_launcher_is_single_current_entrypoint',
    'api/tests/test_v52929_action_lock_vehicle_selection.py::test_v52929_vehicle_selection_is_unambiguous',
    'api/tests/test_v52930_persistent_selection.py::test_v52930_vehicle_selection_is_stronger_and_persistent',
    'api/tests/test_v52932_routage_grand_gabarit_fail_safe.py::test_lanceur_utilise_la_version_courante_pour_casser_le_cache',
    'api/tests/test_v52937_portrait_barre_compacte.py::test_v52936_version_and_launcher',
    'api/tests/test_v52938_coque_standardisee.py::test_version_and_launcher',
    'api/tests/test_v52938_coque_standardisee.py::test_standard_shell_navigation_order',
    'api/tests/test_v52939_branding_shell.py::test_version_and_launcher',
    'api/tests/test_v52939_branding_shell.py::test_shell_order_and_brand_slot',
    'api/tests/test_v52940_standard_ui_pro.py::test_ready_information_and_actions_stay_present',
    'api/tests/test_v52944_fullscreen_corrige.py::test_version_and_launcher_44',
    'api/tests/test_v52945_pwa_wp35.py::test_version_launcher_v52945',
    'api/tests/test_v52945_pwa_wp35.py::test_pwa_manifest_display_orientation_libre',
    'api/tests/test_v52945_pwa_wp35.py::test_pwa_service_worker_and_install_ui',
    'api/tests/test_v52945_pwa_wp35.py::test_launcher_adb_reverse_localhost',
    'api/tests/test_v52948_compact_pwa.py::test_v52948_ready_buttons_preserved',
    'api/tests/test_v52949_finition_pwa.py::test_v52949_version_and_launcher',
    'api/tests/test_v52950_standard_bottom_gap.py::test_v52950_version_launcher',
    'api/tests/test_v52951_keyboard_and_heartbeat.py::test_v52951_version_and_launcher',
    'api/tests/test_v52951_keyboard_and_heartbeat.py::test_keyboard_controller_keeps_destination_visible',
    'api/tests/test_v52951_keyboard_and_heartbeat.py::test_only_keyboard_controller_uses_visualviewport_resize',
    'api/tests/test_v52951_keyboard_and_heartbeat.py::test_service_worker_cache_rotated_for_v52951',
    'api/tests/test_v52952_continuite_stable.py::test_ready_action_continuity_modifier_then_start',
    'api/tests/test_v52952_continuite_stable.py::test_sw_cache_bumped',
    'api/tests/test_v52953_pwa_adb_update.py::test_manifest_start_url_is_current',
    'api/tests/test_v52953_pwa_adb_update.py::test_sw_never_serves_stale_document',
    'api/tests/test_v52955_vehicle_idle_and_system_bar.py::test_vehicle_characteristics_are_permanent_and_locked_at_rest',
    'api/tests/test_v52956_guidage_sous_coque.py::test_v52956_lanceur_court_et_versionne',
    'api/tests/test_v52958_compact_reference_standalone.py::test_manifest_prefers_fullscreen_with_fixed_shell',
    'api/tests/test_v52959_fixed_shell_and_map_order.py::test_pwa_fullscreen_primary_again',
    'api/tests/test_v52960_driving_android_stability.py::test_android_bar_resize_never_shrinks_shell',
    'api/tests/test_v52961_wp35_finition.py::test_single_shell_authority_ignores_same_orientation_resize',
    'api/tests/test_v52978_wp35_recovery.py::test_version_78_everywhere',
    'api/tests/test_v529205_finish_home_input.py::test_itinerary_uses_real_input_not_whole_card_overlay',
    'api/tests/test_v529205_finish_home_input.py::test_enter_validates_active_business_form',
    'api/tests/test_v529205_finish_home_input.py::test_landscape_keyboard_uses_visual_viewport_only_during_edit',
    'api/tests/test_v529206_validation_explicit.py::test_android_enter_uses_same_validation_path',
}

def pytest_collection_modifyitems(config, items):
    for item in items:
        if item.nodeid in LEGACY_V201_RETIRED:
            item.add_marker(pytest.mark.skip(reason="Contrat UI/version historique retiré par l’architecture V201 à 2 vues"))
