[pytest]
testpaths = api/tests
pythonpath = .
markers =
    navigation: tests groupés du bloc Navigation / Itinéraire
    data_route: test groupé du bloc Données route
    restrictions_ui: test groupe restrictions alertes themes interface
    chauffeur: tests groupés du bloc chauffeur
addopts = -ra
